### ISSUE TITLE
How did you add your boiler/thermostat to openhab?

### ISSUE THREAD

**Issue by amateo** [richbeales/openhab-cfg#2]
Hello,

  I have found through [your blog](http://blog.richbeales.net/2014/10/my-z-wave-and-openhab-configuration.html) that you have successfully included a horstmann hrt4-zw thermostat and its related asr-zw boiler switch to openhab.

  Now I'm trying to add a Secure SCS317 (fka hrt4-zw) and SSR303 (fka asr-zw) to mine but I'm having some problems.

  When I connected the boiler switch and the thermostat, boiler LEDs were indicating than there were no z-wave connection. Then, as explained in its manual, I have pressed and holded the network button (previously I have configure openhab in include mode), but although there were logs are my openhab.log, the device hasn't been included.

  Then I have tried with the thermostat, and this time I have included in openhab, but the device is never waken up, so openhab didn't receive any information (I have copied your item configurations, changing the zwave id). With this configuration I can't neither associate the thermostat with the switch (I guess because it hopes the switch connected to a z-wave controller instead of directly connected).

  Did you have to proceed in any special way to add these devices to your openhab?

**Comment by richbeales** [comment]
Yes, there is - and I won't pretend it's easy, but it is possible as both my father and I have done it. Ignore the manual, you won't want to associate the two devices together, but instead add both to openhab.  Habmin is very useful for this as you can see what devices are working and which are orphans.  These instructions helped me http://forum.micasaverde.com/index.php?topic=14646.0 
You need "L" rather than "l" on the thermostat to add them to stop them forming their own little network.

**Comment by richbeales** [comment]
@amateo can I close this issue?

**Comment by amateo** [comment]
Yes, sure.
